# NumPy Essentials

**Arrays & dtypes**

  - homogeneous, fixed-size elements; shapes describe dimensions.

**Creation**

  - `array`, `arange`, `linspace`, `zeros`/`ones`/`full`.

**Indexing & slicing**

  - views for slices; boolean masks select copies.

**Vectorization & ufuncs**

  - elementwise ops without Python loops.

**Broadcasting**

  - align shapes to compute across axes without explicit repeats.

**Reshaping**

  - `reshape`, `ravel`/`flatten`; know when you get a view vs copy.

**Random & reductions**

  - `default_rng`, `mean`/`sum`/`std` with `axis=`.

**Linear algebra**

  - `@`/`dot`, norms, `solve`/`lstsq`, eigenvalues/eigenvectors, SVD, QR/Cholesky, batched ops.

## Arrays & dtypes

In [2]:
import numpy as np

In [3]:
a = np.array([[1., 2., 3.],
            [4., 5., 6.]], dtype=np.float64)

In [4]:
a.shape, a.ndim, a.dtype, a.itemsize

((2, 3), 2, dtype('float64'), 8)

## Creating Arrays

In [5]:
np.array([1, 2, 3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [6]:
np.zeros((2, 3)), np.ones(3), np.full((2, 2), 7)

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([1., 1., 1.]),
 array([[7, 7],
        [7, 7]]))

In [8]:
a = np.arange(12).reshape(3, 4)

In [9]:
a[:, 1:3]  # slice -> view

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [10]:
view = a[:, 1:3]; view[:] = -1; a  # changed original

array([[ 0, -1, -1,  3],
       [ 4, -1, -1,  7],
       [ 8, -1, -1, 11]])

In [11]:
mask = a % 2 == 0

In [12]:
picked = a[mask]

In [13]:
picked[:3] = 99; a[0, 0]  # original unchanged

np.int64(0)

## Vectorization and ufuncs

In [14]:
x = np.linspace(0, 2 * np.pi, 5)

In [15]:
np.sin(x) + np.cos(x)

array([ 1.,  1., -1., -1.,  1.])

In [16]:
xs = np.arange(6).reshape(2, 3)

In [17]:
xs * 2 + 1  # vectorized arithmetic

array([[ 1,  3,  5],
       [ 7,  9, 11]])

## Broadcasting

In [18]:
a = np.array([[1., 2., 3.],
              [4., 5., 6.]])  # shape (2, 3)

In [19]:
b = np.arange(3)  # shape(3,)

In [20]:
a + b  # broadcasts across columns

array([[1., 3., 5.],
       [4., 6., 8.]])

In [21]:
c = np.array([10., 20.])[:, None]  # shape(2, 1)

In [22]:
a + c  # broadcasts down rows

array([[11., 12., 13.],
       [24., 25., 26.]])

## Reshaping and Views

In [23]:
x = np.arange(6)

In [24]:
y = x.reshape(2, 3)  # usually a view

In [25]:
y[0, 0] = 99; x

array([99,  1,  2,  3,  4,  5])

In [26]:
z = x[[0, 1, 2]]  # fancy indexing -> copy

In [27]:
z[0] = -1; x[0]

np.int64(99)

## Random and Reductions

In [28]:
rng = np.random.default_rng(0)

In [29]:
data = rng.normal(size=(3, 4))

In [30]:
data.mean(), data.mean(axis=0), data.std(axis=1)

(np.float64(0.022070802113584375),
 array([-0.3712248 , -0.34531043,  0.44038274,  0.36443569]),
 array([0.28191041, 0.69580564, 0.46359445]))

## Linear Algebra: Vectors, Matrices, and Norms

In [31]:
import numpy as np

In [32]:
v = np.array([3.0, 4.0])  # shape (2,)

In [33]:
M = np.array([[1.0, 2.0],
              [3.0, 4.0]])  # hape (2, 2)

In [34]:
v.shape, M.shape

((2,), (2, 2))

In [35]:
v @ v  # dot/inner product

np.float64(25.0)

In [36]:
np.linalg.norm(v), np.sqrt(v @ v)

(np.float64(5.0), np.float64(5.0))

In [37]:
M @ v  # matrix-vector

array([11., 25.])

In [38]:
M @ M

array([[ 7., 10.],
       [15., 22.]])

In [39]:
v[:, None] @ v[None, :]  # outer -> (2, 2)

array([[ 9., 12.],
       [12., 16.]])

## Matrix Operations: Transpose, Identity, Diagonal

In [41]:
I = np.eye(3)

In [42]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])

In [43]:
a.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [44]:
np.diag([10, 20, 30])

array([[10,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, 30]])

## Solving Systems and Least Squares

In [46]:
A = np.array([[3., 2.], [1., 2.]])

In [47]:
b = np.array([5., 5.])

In [48]:
x = np.linalg.solve(A, b)

In [50]:
x, A @ x, np.allclose(A @ x, b)

(array([0. , 2.5]), array([5., 5.]), True)

In [59]:
# Least squares fit y = alpha*x + beta
X = np.c_[np.arange(5), np.ones(5)]  # design: columns [x, 1]
y = np.array([0., 1., 2.2, 2.9, 4.1])
coeffs, *_ = np.linalg.lstsq(X, y, rcond=None)
alpha, beta = coeffs

In [60]:
alpha, beta

(np.float64(1.01), np.float64(0.01999999999999924))

In [61]:
residual = np.linalg.norm(X @ coeffs - y)

In [62]:
residual

np.float64(0.22583179581272453)

## Eigenvalues, Eigenvectors, and SVD

In [64]:
S = np.array([[2., 1.], [1., 2.]])  # symetric 

In [65]:
w, U = np.linalg.eigh(S) # S = U diag(w) U.T

In [67]:
np.allclose(S @ U, U @ np.diag(w)) # same as broadcasting U * w

True

In [68]:
M = np.array([[1., 2., 3.], [4., 5., 6.]])

In [69]:
U, s, Vt = np.linalg.svd(M, full_matrices=False)

In [70]:
np.allclose(M, U @ np.diag(s) @ Vt)

True

In [71]:
k = 1; Mk = U[:, :k] @ np.diag(s[:k]) @ Vt[:k]

In [72]:
np.linalg.norm(M - Mk) # best rank-1 error

np.float64(0.7728696356734843)

## QR and Cholesky

In [74]:
A = np.array([[1., 1.], [1., 2.], [1., 3.]]) # 3x2 design

In [75]:
Q, R = np.linalg.qr(A)

In [76]:
np.allclose(A, Q @ R), np.allclose(Q.T @ Q, np.eye(2))

(True, True)

In [77]:
SPD = np.array([[4., 2.], [2., 3.]])

In [78]:
L = np.linalg.cholesky(SPD) # SPD = L @ L.T

In [79]:
np.allclose(SPD, L @ L.T)

True

## Batch Linear Algebra and einsum

In [80]:
A = np.random.default_rng(0).normal(size=(10, 2, 2)) # 10 small systems

In [81]:
x = np.ones((10, 2, 1))

In [82]:
y = A @ x # batch matmul -> shape (10, 2, 1)

In [83]:
y.shape

(10, 2, 1)

In [85]:
# Einsum: outer product then reduction
u = np.array([1., 2., 3.])
v = np.array([10., 20., 30.])
outer = np.einsum('i,j->ij', u, v)

In [86]:
outer

array([[10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [87]:
total = np.einsum('ij->', outer)  # sum all elements

In [88]:
total

np.float64(360.0)

## Performance Notes

- Prefer vectorized ops and ufuncs over Python lops.

- Avoid creating large temporary arrays; fuse operations or use `out=` when available.

- Keep arrays continguous where possible; be aware of copies from fancy indexing.

- Use `float64` for numeric stability when in doubt; profile memory/time if large.

## Mental Models & Pitfalls

**Shapes as contracts**

- know the `shape` of every array; mismatches cause subtle bugs.

**Views vs copies**

- slices are windows onto the same data; boolean/fancy indexing returns a copy.

**Row vs column**

- `(n,)` is not `(n,1)`; use `None` or `np.newaxis` to add axes.

**Dtypes matter**

- integer division produces floats with`/`; watch for implicit up/down-casts.

**Broadcasting intuition**

- align trailing axes; extend length-1 to match.

## Common Gotchas

**Silent copies**

- operations like `x[[...]]` or `x[x>0]` return copies; in-place edits won't affect the original.

**Chained indexing**

- avoid `a[a>0][0]`; you index a temporary copy. Use a single index or `np.where`.

**Mixed dtypes**

- constructing from mixed Python types can yield `object` dtype; specify `dtype=` or cast.

**Over-reshaping**

- `reshape` keeps the same number of elements; use `-1` to infer one dimension safely.

**In-place with broadcasting**

- edits on broadcasted views may fail or surprise; assign into a slice with matching shape.

## Exercises

**Warm-up shapes**

Create `a = np.arange(12).reshape(3, 4)` and report `a.shape`, `a.ndim`, and the last row using slicing.

In [90]:
a = np.arange(12).reshape(3, 4)
a.shape, a.ndim, a[-1, :]

((3, 4), 2, array([ 8,  9, 10, 11]))

**Masking practice**

With `a` above, set all odd numbers to `-1` using a boolean mask.

In [91]:
a[a % 2 != 0] = -1
a

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

**Broadcasting row/column**

Make `x = np.arange(3)` and `y = np.arange(2)[:, None]`. Compute `x + y` and explain the resulting shape.

In [92]:
x = np.arange(3); x

array([0, 1, 2])

In [93]:
y = np.arange(2)[:, None]; y

array([[0],
       [1]])

In [94]:
x + y

array([[0, 1, 2],
       [1, 2, 3]])

This result occurs because the columns of `x` are broadcast across the rows of `y`.

**Standardize columns**

Given `X` shape `(m,n)`, subtract the column means and divide by column stds without loops.

In [5]:
rng = np.random.default_rng(42)

m, n = 3, 4
X = rng.normal(size=(m, n))

( X - X.mean(axis=0, keepdims=True) ) / X.std(axis=0)

array([[ 0.86230327,  0.13617296,  0.50146991,  0.84791162],
       [-1.40188579, -1.2871405 , -1.39589693, -1.40415192],
       [ 0.53958252,  1.15096754,  0.89442702,  0.5562403 ]])

**Views vs copies**

Show that `X[:, :2]` is a view by modifying it and inspecting `X`. Show that `X[X>0]` is a copy by attempting an in-place change.

In [6]:
X = np.array(np.arange(16)).reshape(4,4); X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
A = X[:, :2]; A

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [8]:
A[A % 2 == 1] = -3
A, X

(array([[ 0, -3],
        [ 4, -3],
        [ 8, -3],
        [12, -3]]),
 array([[ 0, -3,  2,  3],
        [ 4, -3,  6,  7],
        [ 8, -3, 10, 11],
        [12, -3, 14, 15]]))

In [10]:
B = X[X>0]
B[3] = 24
B, X

(array([ 2,  3,  4, 24,  7,  8, 10, 11, 12, 14, 15]),
 array([[ 0, -3,  2,  3],
        [ 4, -3,  6,  7],
        [ 8, -3, 10, 11],
        [12, -3, 14, 15]]))

**Matrix multiply**

Build `A` shape `(2,3)` and `B` shape `(3,2)` and compute `A @ B`. Verify the shape and a single entry by hand.

In [11]:
A = np.array( np.arange(6) + 10 ).reshape(2, 3); A

array([[10, 11, 12],
       [13, 14, 15]])

In [12]:
B = np.array( np.arange(6) + 30 ).reshape(3, 2); B

array([[30, 31],
       [32, 33],
       [34, 35]])

In [13]:
C = A @ B
assert C[0, 0] == 1060
assert C[-1, -1] == 1390
C

array([[1060, 1093],
       [1348, 1390]])